#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npx lint-staged ||
(
    echo '🤢🤮🤢🤮 Its RAW - You Failed Style and Lint checking 🤢🤮🤢🤮';
    false;
)
# If everything passes... Now we can commit
echo '✅✅✅✅ You Passed this time... I am committing this now. ✅✅✅✅'